name: Build PBW
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Write env.js
      run: |
        echo "module.exports = {STADIAMAPS_API_KEY: '${{ secrets.STADIAMAPS_API_KEY }}'}" > env.js
    - name: Install Pebble CLI
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv tool install pebble-tool --python 3.13
    - name: Install Pebble SDK
      run: |
        pebble sdk install ${{ vars.PEBBLE_SDK_VERSION }}
    - name: Build PBW
      run: |
        pebble build
    - name: Upload PBW Artifact
      uses: actions/upload-artifact@v6
      with:
        name: pebbletrail-pbw
        path: build/PebbleTrail.pbw
    - name: Cache Pebble Tool
      uses: actions/cache@v5
      with:
        path: /home/runner/.pebble-sdk/
        key: pebble-sdk-${{ vars.PEBBLE_SDK_VERSION }}
