name: Build PBW
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Pebble SDK
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv tool install pebble-tool --python 3.13
    - name: Build PBW
      run: |
        pebble build
    - name: Upload PBW Artifact
      uses: actions/upload-artifact@v6
      with:
        name: pebbletrail-pbw
        path: build/pebbletrail.pbw
